name: uaepass_example
description: "Demonstrates how to use the uaepass plugin."
version: 0.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uae_pass:
    path: ../

dev_dependencies:


flutter:
  uses-material-design: true