name: uae_pass
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  appcheck: ^1.1.0
  connectivity_plus: ^5.0.2
  dartz: 0.10.1
  dio: ^5.4.1
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_custom_utility: ^0.0.10
  flutter_bloc: ^8.1.4
  flutter_localization: ^0.2.0
  flutter_inappwebview: ^6.0.0
  get_it: ^7.6.7
  logger: ^2.0.2+1
  permission_handler: ^11.3.0
  plugin_platform_interface: ^2.0.2
  store_redirect: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.uaepass.uaepass
        pluginClass: UaepassPlugin
      ios:
        pluginClass: UaepassPlugin

  assets:
    - assets/cert/qa_uaepass.pem
    - assets/cert/prod_uaepass.pem
    - assets/lang/lang_en.json
    - assets/lang/lang_ar.json
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: GEFlow
      fonts:
        - asset: assets/fonts/GEFlow.otf
        - asset: assets/fonts/GEFlowBold.otf
