name: ft_uaepass
description: "This package allows the Flutter app to integrate the UAE pass."

version: 0.0.5+5
homepage: https://jarvistechnolabs.com/
repository: https://github.com/Jarvis-Technolabs/uae_pass

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  appcheck: ^1.1.0
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localization: ^0.2.0
  flutter_inappwebview: ^6.0.0
  get_it: ^7.7.0
  http: ^1.2.1
  logger: ^2.0.2+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  plugin_platform_interface: ^2.0.2
  store_redirect: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.uaepass.uaepass
        pluginClass: UaepassPlugin
      ios:
        pluginClass: UaepassPlugin

  assets:
    - assets/cert/qa_uaepass.pem
    - assets/cert/prod_uaepass.pem
    - assets/lang/lang_en.json
    - assets/lang/lang_ar.json
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: GEFlow
      fonts:
        - asset: assets/fonts/GEFlow.otf
        - asset: assets/fonts/GEFlowBold.otf
