name: uae_pass
description: "UAE pass flutter package."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  appcheck: ^1.1.0
  auto_size_text: 3.0.0
  avatar_view: 1.0.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  dartz: 0.10.1
  device_info_plus: ^9.1.2
  device_preview: 1.1.0
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  drift: ^2.15.0
  encrypt: ^5.0.3
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption
  equatable: 2.0.5
  flutter_custom_utility: ^0.0.5
  flutter_bloc: ^8.1.4
  flutter_jailbreak_detection: 1.10.0
  flutter_local_notifications: ^16.3.2
  flutter_localization: ^0.2.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^6.0.0
  get_it: ^7.6.7
  hive: 2.2.3
  hive_flutter: 1.1.0
  hive_generator: ^2.0.1
  image_and_file_picker_utility: ^0.0.1
  jt_flutter_cli: ^1.3.0
  keyboard_actions: ^4.2.0
  logger: ^2.0.2+1
  logging: 1.2.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  shimmer: 3.0.0
  sign_in_with_apple: 5.0.0
  store_redirect: 2.0.1
  super_tooltip: ^2.0.7
  webview_flutter: ^4.7.0


dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: 0.13.1
  pubspec_dependency_sorter: ^1.0.4
  retrofit_generator: ^8.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
