name: uae_pass
description: "UAE pass flutter package."
version: 0.0.1
homepage: https://jarvistechnolabs.com/
repository: https://github.com/Jarvis-Technolabs/uae_pass

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  appcheck: ^1.1.0
  connectivity_plus: ^5.0.2
  dartz: 0.10.1
  dio: ^5.4.1
  equatable: 2.0.5
  flutter_custom_utility: ^0.0.5
  flutter_bloc: ^8.1.4
  flutter_localization: ^0.2.0
  flutter_inappwebview: ^6.0.0
  get_it: ^7.6.7
  logger: ^2.0.2+1
  permission_handler: ^11.3.0
  store_redirect: 2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/cert/